---

- include_tasks: prepare.yaml

- include: install.yml
  tags:
    - configuration
    - ufw
    - ufw-install

- include: configure.yml
  tags:
    - configuration
    - ufw
    - ufw-configure

- include: service.yaml
  tags:
    - configuration
    - ufw
    - ufw-start-enable-service

...
